-- payment-service schema: payment (owned by this service's database).
-- order_id is a bare id from order-service (unique: one payment per order),
-- with NO cross-service FK (Database per Service).

CREATE TABLE payment (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT         NOT NULL,
    owner_username VARCHAR(50)    NOT NULL,
    amount         NUMERIC(12, 2) NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    paid_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_payment_order UNIQUE (order_id),
    CONSTRAINT chk_payment_status CHECK (status IN ('SUCCESS', 'FAILED'))
);
