-- book-service schema: author + book (owned by this service's database only).

CREATE TABLE author (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE book (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255)   NOT NULL,
    isbn       VARCHAR(32)    NOT NULL,
    price      NUMERIC(10, 2) NOT NULL,
    stock      INTEGER        NOT NULL,
    author_id  BIGINT         NOT NULL,
    version    BIGINT         NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_book_isbn UNIQUE (isbn),
    CONSTRAINT chk_book_stock_non_negative CHECK (stock >= 0),
    CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author (id)
);

CREATE INDEX idx_book_author_id ON book (author_id);
CREATE INDEX idx_book_title ON book (title);
