-- Phase 2 initial schema: author + book.
-- Schema is owned by Flyway; the app runs with ddl-auto=validate (never update).

CREATE TABLE author (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE book (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255)   NOT NULL,
    isbn       VARCHAR(32)    NOT NULL,
    price      NUMERIC(10, 2) NOT NULL,
    stock      INTEGER        NOT NULL,
    author_id  BIGINT         NOT NULL,
    version    BIGINT         NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_book_isbn UNIQUE (isbn),
    CONSTRAINT chk_book_stock_non_negative CHECK (stock >= 0),
    CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author (id)
);

-- Supports FK joins and "books by a given author" lookups (incl. the N+1 fetch-join).
CREATE INDEX idx_book_author_id ON book (author_id);

-- Supports catalog search/sort by title (GET /api/books keyword search, later phases).
CREATE INDEX idx_book_title ON book (title);
