-- order-service schema: orders + order_item (owned by this service's database).
-- The FK is intra-service (order_item -> orders). book_id is a bare id from
-- book-service with NO cross-service FK (Database per Service).

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_username VARCHAR(50)    NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    total_price    NUMERIC(12, 2) NOT NULL,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT chk_orders_status CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'SHIPPED'))
);

CREATE TABLE order_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL,
    book_id    BIGINT         NOT NULL,
    quantity   INTEGER        NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT chk_order_item_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_orders_owner ON orders (owner_username);
CREATE INDEX idx_order_item_order_id ON order_item (order_id);
